### ISSUE TITLE
Deadlock (nothing happening) in multi-GPU setting

### ISSUE THREAD

**Issue by ayulockin** [CarperAI/trlx#34] opened 2022-10-17 05:38 UTC
Hey all, I am using this [colab notebook](https://colab.research.google.com/drive/1LWz_0xtH4OPkRytO34sdyZTqI4K52njY?usp=sharing#scrollTo=SoNdzrJLfCo-) as a reference (that I found in the discord server) to train `examples/ppo_sentiments.py` using HF Accelerate in a GCP VM with 2 K80s. 

This is my `accelerate config`:

```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
gpu_ids: '[all]'
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
```

Unfortunately, nothing happens after this point, as shown in the image:

<img width="941" alt="image" src="https://user-images.githubusercontent.com/31141479/196096788-b45f637a-d658-4fa4-a99c-b39ec391e411.png">

To avoid getting this warning, `huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...`, I set `TOKENIZERS_PARALLELISM=false`.  

I am not an expert in using Accelerate; any help would be appreciated. Also, for context, I am trying to run this example to build W&B sweeps (hyperparameter optimization), mentioned in #12.

cc: @LouisCastricato

**Comment by LouisCastricato** [comment] 2022-10-17 11:54
@Dahoas @reciprocated

**Comment by reciprocated** [comment] 2022-10-17 14:43
Can reproduce this. `gpu_ids: '[all]'` in the config doesn't put anything on gpu. So it's not a deadlock, but rather the training on cpu is progressing very slowly. Interesting to see which version of accelerate have you used to generate this config. Correct version on 0.13.0 is `gpu_ids: all` or removing the line altogether. However I also uncovered that our ddp intergration is lacking in another way, I'll have a separate issue for that, in the meantime if you want multigpu here's the config which works on this example:
```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 1
distributed_type: DEEPSPEED
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
use_cpu: false
```

And just in case you don't have to burn gcp credits to test sweeps, since you can run examples without accelerate's launchers and also locally on cpu if you don't expect the training to complete. Good luck!

**Comment by ayulockin** [comment] 2022-10-17 19:12
> Interesting to see which version of accelerate have you used to generate this config.

I am on 0.13.1.

**Comment by ayulockin** [comment] 2022-10-17 19:40
Okay, so to test if the training was happening on the CPU instead of the GPU, in the `configs/ppo_config.yml`, I changed `epochs`:1 and `total_steps`:1. I thought that maybe even on the CPU, a single step will not take forever. Unfortunately, nothing is happening. Let me share more details.

```
>>> accelerate env

- `Accelerate` version: 0.13.1
- Platform: Linux-4.19.0-22-cloud-amd64-x86_64-with-debian-10.13
- Python version: 3.7.12
- Numpy version: 1.21.6
- PyTorch version (GPU?): 1.12.1 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: None
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 1, 'gradient_clipping': 1.0, 'zero3_init_flag': False, 'zero_stage': 1}
        - fsdp_config: {}
        - downcast_bf16: no
````

Here's the stdout [logs](https://wandb.ai/ayush-thakur/trlx-examples/runs/1okdu7go/logs?workspace=user-ayut) logged to W&B. Maybe you can notice something useful in the logs.

Finally, to confirm if the training was happening on the CPU, here are the [system metrics](https://wandb.ai/ayush-thakur/trlx-examples/runs/1okdu7go/system?workspace=user-ayut). Notice that CPU and GPU utilizations are zero.

Let me try downgrading Accelerate to `0.13.0`. I will also try a simple accelerate example on my VM to assure that the issue is not with my machine.

cc: @reciprocated

**Comment by reciprocated** [comment] 2022-10-17 20:36
This is an interesting datapoint, can you check your setup with this example?
```python
import os
import torch
import accelerate

def main():
    accelerator = accelerate.Accelerator()

    model = torch.nn.Linear(10, 10)
    dataloader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(torch.ones(10)))
    opt = torch.optim.Adam(model.parameters())

    print(f'... prepare')
    model, opt, dataloader = accelerator.prepare(model, opt, dataloader)
    print(f'prepare ...')

    out = model(torch.ones(10, device=accelerator.device))
    print(out.device)

    x = torch.full((1,), int(os.environ.get('LOCAL_RANK')), device=accelerator.device)
    print(f'... gather')
    gathered = accelerate.utils.gather(x)
    print(f'gather ...')
    print(gathered)

if __name__ == '__main__':
    main()
```

**Comment by ayulockin** [comment] 2022-10-17 21:46
my setup seems to work with the example you shared (thank you). Below, I have shared a final few lines from stdout.

```
prepare ...
cuda:1
1
... gather
gather ...
cuda:0
0
... gather
gather ...
tensor([100, 100], device='cuda:1')
tensor([100, 100], device='cuda:0')
```

**Comment by LouisCastricato** [comment] 2022-10-19 19:04
@ayulockin did you resolve this

**Comment by ayulockin** [comment] 2022-10-21 02:06
Hey @reciprocated @LouisCastricato I resloved this finally. 

I created a new VM (deleted older one) and did a fresh installation of trlx. With the following accelerate config;

```
- `Accelerate` version: 0.13.2
- Platform: Linux-4.19.0-22-cloud-amd64-x86_64-with-glibc2.28
- Python version: 3.9.13
- Numpy version: 1.23.4
- PyTorch version (GPU?): 1.12.1+cu102 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: None
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 1, 'gradient_clipping': 1.0, 'offload_optimizer_device': 'cpu', 'offload_param_device': 'cpu', 'zero3_init_flag': False, 'zero_stage': 2}
        - fsdp_config: {}
        - downcast_bf16: no
```

it's working as expected (however 2 GPUs are slower than 1). Since I tried multiple thing, I cannot pin point on exact fix of this issue. Or it might just be my VM not behaving properly. Anyway I lost enough time on it so moving ahead to build something on top of it.

**Comment by LouisCastricato** [comment] 2022-10-21 02:40
The two GPUs being slower than one is odd. @Dahoas known issue?

Thanks, sorry for the trouble with debugging this. Let's close this issue I think. Alex make a new issue about the two GPUs being slower than one if you think it's necessary.

**Closed** 2022-10-21 02:40 UTC
