### ISSUE TITLE
(perhaps) data preparation bug in RLHF

### ISSUE THREAD

**Issue by xwwwwww** [CarperAI/trlx#297] opened 2023-02-09 12:06 UTC
### 🐛 Describe the bug

I have several problems about data preparations while running `summarize_rlhf`.

1. In `get_prompt_dataset` https://github.com/CarperAI/trlx/blob/f115eeaa3cfd2c997a345b8891b5f9427f1a08ee/examples/summarize_rlhf/trlx_gptj_text_summarization.py#L58
Current implementations will first truncate the original prompts with `max_length-5`. However, I notice that the tokenized results of the prompts will change after appending `\nTL;DR:` in some cases, which then lead to the truncation of the suffix of `\nTL;DR:` and finally lead to keyerror in https://github.com/CarperAI/trlx/blob/f115eeaa3cfd2c997a345b8891b5f9427f1a08ee/examples/summarize_rlhf/trlx_gptj_text_summarization.py#L83

2. Even after I fix this truncation bug in `get_prompt_dataset`, current implementations will still raise keyerror in https://github.com/CarperAI/trlx/blob/f115eeaa3cfd2c997a345b8891b5f9427f1a08ee/examples/summarize_rlhf/trlx_gptj_text_summarization.py#L83 during PPO training.

### Which trlX version are you using?

main

### Additional system and package information

transformers==4.26.0

**Comment by LouisCastricato** [comment] 2023-02-09 12:07
@PhungVanDuy

**Comment by LouisCastricato** [comment] 2023-02-09 12:07
Thanks, we will investigate

**Comment by LouisCastricato** [comment] 2023-02-09 12:28
We should freeze our transformers version maybe... just update it every major TRLX release.

**Comment by PhungVanDuy** [comment] 2023-02-09 12:30
> 

Yes, even with the torch version, accelerate,... some people raised errors when they ran on different versions with us.

**Comment by xwwwwww** [comment] 2023-02-09 12:47
>  I suggested you change the function with this style: https://github.com/CarperAI/trlx/blob/main/examples/summarize_daily_cnn/t5_summarize_daily_cnn.py#L25, to make sure the KeyError not happened again. I will make a new version of this examples soon to prevent this error happened again.

Could you please provide more detailed instructions on how to fix the above issue? I didn't see clear difference between https://github.com/CarperAI/trlx/blob/main/examples/summarize_daily_cnn/t5_summarize_daily_cnn.py#L25 and current implementations of `summarize_rlhf` :)

**Comment by xwwwwww** [comment] 2023-02-09 12:51
by the way, I have tried `transformers=4.25.1` and it still raises KeyError

**Comment by xwwwwww** [comment] 2023-02-09 12:54
For the first issue about truncation, a quick way to test is add another line of

```python
assert tmp.endswith("TL;DR:")
``` 
under https://github.com/CarperAI/trlx/blob/f115eeaa3cfd2c997a345b8891b5f9427f1a08ee/examples/summarize_rlhf/trlx_gptj_text_summarization.py#L78

Could this assertion pass in your environment?

**Comment by PhungVanDuy** [comment] 2023-02-09 12:56
> For the first issue about truncation, a quick way to test is add another line of
> 
> ```python
> assert tmp.endswith("TL;DR:")
> ```
> 
> under
> 
> https://github.com/CarperAI/trlx/blob/f115eeaa3cfd2c997a345b8891b5f9427f1a08ee/examples/summarize_rlhf/trlx_gptj_text_summarization.py#L78
> 
> Could this assertion pass in your environment?

I am quick wrap-up the solution for you!

**Comment by xwwwwww** [comment] 2023-02-09 14:54
It is the KeyError raised in `post_summary_dict[text.strip()]`. 
Specifically, I observe that it could be caused by the truncation problem and some other problems.

**Comment by xwwwwww** [comment] 2023-02-09 15:19
By the way, I traverse all the prompts before training to check if this KeyError will be raised by adding the following code after this line
https://github.com/CarperAI/trlx/blob/f115eeaa3cfd2c997a345b8891b5f9427f1a08ee/trlx/trlx.py#L92

```python
pipeline = get_pipeline(config.train.pipeline)(prompts, max_prompt_length, trainer.tokenizer)
orch = get_orchestrator(config.train.orchestrator)(trainer, pipeline, chunk_size=config.method.chunk_size)

# debug code
for batch in tqdm(orch.pipeline_iterator):
    prompt_tensors = batch.input_ids
    samples = copy(prompt_tensors)
    str_samples, str_prompts, str_outputs = trainer.decode(prompt_tensors, samples)
    trainer.reward_fn(
            samples=str_samples,
            prompts=str_prompts,
            outputs=str_outputs,
        )
```

**Comment by xwwwwww** [comment] 2023-02-09 15:33
emm so what is the difference exactly and how could we fix it :)

**Comment by PhungVanDuy** [comment] 2023-02-09 15:39
I don't really know exactly what case you getting KeyError, because I was aware of this error and make it work already that why I am able to train it before. Maybe some change from new updates broke it. Can you print out the examples when `KeyError` happened when you run PPO?

**Comment by xwwwwww** [comment] 2023-02-09 15:42
Here is an example:

```
  File "trlx_gptj_text_summarization.py", line 104, in <listcomp>
    original_samples = [text + post_summary_dict[text.strip()] for text in original_samples]
KeyError: 'SUBREDDIT: r/tifu\nTITLE: TIFU by doing a recursive delete\nPOST: I\'ve been writing a PowerShell script to find and delete redundant $RECYCLE.BIN files in our thousands of user personal folders.  \n\nThe script is going well. It works perfectly fine. It takes a matter of minutes and gives beautiful log and error output info.  \n\nThen I notice that I\'m not using the same standardised variable name for the folder I\'m trying to clear out, so I edit one of my functions to bring it into line. Great, now the function should use the right variable name.  \n\nI run the script and check my error logs. Instead of the 78 KB file I\'m expecting (from previous runs it was that size), I get a 4.9 MB file. Shit.  \n\nI check the file and see that it\'s got errors like "Unable to delete C:\\WINDOWS. Folder not empty". Fuck.  \n\nI check other folders on the server and notice they\'re also empty. Hardly any files to be found. It\'s like a digital ghost town.\nI check my code again and see that I forgot to change the variable on the line that does the actual deleting:  \n\n ...\n    Remove-Item $Folder\\* -Recurse -Force -ErrorAction SilentlyContinue\n ...\n\nThe function accepted param([string] $Path), not $Folder.\nInstead of PowerShell going "Hey, I see a bug here. Something\'s wrong, so I\'ll stop", it goes straight ahead and does a recursive delete from the root of the C: drive. Anything my script was able to delete, it did.  \n\nI immediately owned up to the problem and got our servers and storage manager to see what he could do.  \n\nThere was no server image to restore from. The backup software on the server wasn\'t working because.. I\'d deleted it. He first had to install the backup software before attempting to do a restore. The restore is still running. The server will be rebooted tomorrow, and if it\'s fine it\'ll be left as-is. If not it\'ll need to be re-done from scratch.  \n\nNo biggie, the server wasn\'t\nTL;DR:'
```

**Comment by PhungVanDuy** [comment] 2023-02-09 16:03
> KeyError: 'SUBREDDIT: r/tifu\nTITLE: TIFU by doing a recursive delete\nPOST: I\'ve been writing a PowerShell script to find and delete redundant $RECYCLE.BIN files in our thousands of user personal folders.  \n\nThe script is going well. It works perfectly fine. It takes a matter of minutes and gives beautiful log and error output info.  \n\nThen I notice that I\'m not using the same standardised variable name for the folder I\'m trying to clear out, so I edit one of my functions to bring it into line. Great, now the function should use the right variable name.  \n\nI run the script and check my error logs. Instead of the 78 KB file I\'m expecting (from previous runs it was that size), I get a 4.9 MB file. Shit.  \n\nI check the file and see that it\'s got errors like "Unable to delete C:\\WINDOWS. Folder not empty". Fuck.  \n\nI check other folders on the server and notice they\'re also empty. Hardly any files to be found. It\'s like a digital ghost town.\nI check my code again and see that I forgot to change the variable on the line that does the actual deleting:  \n\n ...\n    Remove-Item $Folder\\* -Recurse -Force -ErrorAction SilentlyContinue\n ...\n\nThe function accepted param([string] $Path), not $Folder.\nInstead of PowerShell going "Hey, I see a bug here. Something\'s wrong, so I\'ll stop", it goes straight ahead and does a recursive delete from the root of the C: drive. Anything my script was able to delete, it did.  \n\nI immediately owned up to the problem and got our servers and storage manager to see what he could do.  \n\nThere was no server image to restore from. The backup software on the server wasn\'t working because.. I\'d deleted it. He first had to install the backup software before attempting to do a restore. The restore is still running. The server will be rebooted tomorrow, and if it\'s fine it\'ll be left as-is. If not it\'ll need to be re-done from scratch.  \n\nNo biggie, the server wasn\'t\nTL;DR:'

What is your discord ID? It should be easier to discuss, my discord ID: daica#3877

**Comment by jon-tow** [comment] 2023-02-09 16:59
I've reproduced this problem before. The temporary (terrible) hack I used was to truncate the OpenAI summary keys to 272 chars. Something like:

```python
    # NOTE: `num_char_compares` is a hacky way to avoid `KeyError`s when retrieving original summaries because we can't
    # ensure the decoded summaries are the same as the original summaries (non-invertibility of the used tokenizers?)
    num_char_compares = 272  # Only compare the first N chars in the decoded post for safe mapping

    def reward_fn(samples: List[str], **kwargs):
        original_samples = [text.split("TL;DR:")[0] + "TL;DR: " for text in samples]
        # Truncate text before accessing `post_summary_dict`
        original_samples = [text + post_summary_dict[text[:num_char_compares]] for text in original_samples]
        original_scores = get_scores(original_samples)
        scores = get_scores(samples)
        norms_scores = scores - original_scores
        return norms_scores

    # ...

    # Get the OpenAI summaries
    post_summary_dict = {}
    train_prompts = get_prompt_dataset(train_posts, max_length_input)
    for i in range(len(train_prompts)):
        post_summary_dict[train_prompts[i][:num_char_compares]] = train_summaries[i]
    val_prompts = get_prompt_dataset(val_posts, max_length_input)
    for i in range(len(val_prompts)):
        post_summary_dict[val_prompts[i][:num_char_compares]] = val_summaries[i]
    ```

Still looking for a proper fix...

**Comment by cat-state** [comment] 2023-02-09 23:17
the underlying issue appears to be the same as https://github.com/CarperAI/trlx/issues/301

**Comment by xwwwwww** [comment] 2023-02-10 02:42
Moreover, I am also confused by the extra space in this line
https://github.com/CarperAI/trlx/blob/f115eeaa3cfd2c997a345b8891b5f9427f1a08ee/examples/summarize_rlhf/trlx_gptj_text_summarization.py#L82

Why do we append "TL;DR: " instead of "TL;DR:"?

**Comment by xwwwwww** [comment] 2023-02-16 07:59
Hi, do we have a proper solution now :)

**Comment by YingHH1** [comment] 2023-02-17 04:45
> Here is an example:
> 
> ```
>   File "trlx_gptj_text_summarization.py", line 104, in <listcomp>
>     original_samples = [text + post_summary_dict[text.strip()] for text in original_samples]
> KeyError: 'SUBREDDIT: r/tifu\nTITLE: TIFU by doing a recursive delete\nPOST: I\'ve been writing a PowerShell script to find and delete redundant $RECYCLE.BIN files in our thousands of user personal folders.  \n\nThe script is going well. It works perfectly fine. It takes a matter of minutes and gives beautiful log and error output info.  \n\nThen I notice that I\'m not using the same standardised variable name for the folder I\'m trying to clear out, so I edit one of my functions to bring it into line. Great, now the function should use the right variable name.  \n\nI run the script and check my error logs. Instead of the 78 KB file I\'m expecting (from previous runs it was that size), I get a 4.9 MB file. Shit.  \n\nI check the file and see that it\'s got errors like "Unable to delete C:\\WINDOWS. Folder not empty". Fuck.  \n\nI check other folders on the server and notice they\'re also empty. Hardly any files to be found. It\'s like a digital ghost town.\nI check my code again and see that I forgot to change the variable on the line that does the actual deleting:  \n\n ...\n    Remove-Item $Folder\\* -Recurse -Force -ErrorAction SilentlyContinue\n ...\n\nThe function accepted param([string] $Path), not $Folder.\nInstead of PowerShell going "Hey, I see a bug here. Something\'s wrong, so I\'ll stop", it goes straight ahead and does a recursive delete from the root of the C: drive. Anything my script was able to delete, it did.  \n\nI immediately owned up to the problem and got our servers and storage manager to see what he could do.  \n\nThere was no server image to restore from. The backup software on the server wasn\'t working because.. I\'d deleted it. He first had to install the backup software before attempting to do a restore. The restore is still running. The server will be rebooted tomorrow, and if it\'s fine it\'ll be left as-is. If not it\'ll need to be re-done from scratch.  \n\nNo biggie, the server wasn\'t\nTL;DR:'
> ```

I am facing the exact error too. Could there be a possible fix?

**Comment by PhungVanDuy** [comment] 2023-02-17 04:47
> > Here is an example:
> > ```
> >   File "trlx_gptj_text_summarization.py", line 104, in <listcomp>
> >     original_samples = [text + post_summary_dict[text.strip()] for text in original_samples]
> > KeyError: 'SUBREDDIT: r/tifu\nTITLE: TIFU by doing a recursive delete\nPOST: I\'ve been writing a PowerShell script to find and delete redundant $RECYCLE.BIN files in our thousands of user personal folders.  \n\nThe script is going well. It works perfectly fine. It takes a matter of minutes and gives beautiful log and error output info.  \n\nThen I notice that I\'m not using the same standardised variable name for the folder I\'m trying to clear out, so I edit one of my functions to bring it into line. Great, now the function should use the right variable name.  \n\nI run the script and check my error logs. Instead of the 78 KB file I\'m expecting (from previous runs it was that size), I get a 4.9 MB file. Shit.  \n\nI check the file and see that it\'s got errors like "Unable to delete C:\\WINDOWS. Folder not empty". Fuck.  \n\nI check other folders on the server and notice they\'re also empty. Hardly any files to be found. It\'s like a digital ghost town.\nI check my code again and see that I forgot to change the variable on the line that does the actual deleting:  \n\n ...\n    Remove-Item $Folder\\* -Recurse -Force -ErrorAction SilentlyContinue\n ...\n\nThe function accepted param([string] $Path), not $Folder.\nInstead of PowerShell going "Hey, I see a bug here. Something\'s wrong, so I\'ll stop", it goes straight ahead and does a recursive delete from the root of the C: drive. Anything my script was able to delete, it did.  \n\nI immediately owned up to the problem and got our servers and storage manager to see what he could do.  \n\nThere was no server image to restore from. The backup software on the server wasn\'t working because.. I\'d deleted it. He first had to install the backup software before attempting to do a restore. The restore is still running. The server will be rebooted tomorrow, and if it\'s fine it\'ll be left as-is. If not it\'ll need to be re-done from scratch.  \n\nNo biggie, the server wasn\'t\nTL;DR:'
> > ```
> 
> I am facing the exact error too. Could there be a possible fix?

For some reason, I never getting this error. For a quick fix can you use this [hack](https://github.com/CarperAI/trlx/issues/297#issuecomment-1424514752).

**Comment by YingHH1** [comment] 2023-02-17 05:04
The error occurs half-way in the PPO training process, hope these logs are useful in locating the issue:

[losses/total_loss: 0.53 | losses/policy_loss: -0.15 | losses/value_loss: 3.41]:  54%|██████████████████████████████████████████████▉                                        | 3456/6400 [14:30:53<3:14:
06,  3.96s/it][RANK 0] Collecting rollouts
[rollout 128 / 128]: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 128/128 [05:04<00:
00,  2.38s/it]
[losses/total_loss: 0.30 | losses/policy_loss: 0.10 | losses/value_loss: 1.03]:  56%|█████████████████████████████████████████████████▎                                      | 3584/6400 [14:44:25<3:02:
54,  3.90s/it][RANK 0] Collecting rollouts
[rollout 80 / 128]:  62%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                                          | 80/128 [03:10<01:
52,  2.34s/it]

Traceback (most recent call last):
  File "/home/usr1/trlx/examples/summarize_rlhf/trlx_gptj_text_summarization.py", line 88, in reward_fn
    original_samples = [text + post_summary_dict[text.strip()] for text in original_samples]
  File "/home/usr1/trlx/examples/summarize_rlhf/trlx_gptj_text_summarization.py", line 88, in <listcomp>
    original_samples = [text + post_summary_dict[text.strip()] for text in original_samples]
KeyError: 'SUBREDDIT: r/tifu\nTITLE: TIFU by doing a recursive delete\nPOST: I\'ve been writing a PowerShell script to find and delete redundant $RECYCLE.BIN files in our thousands of user personal fo
lders.  \n\nThe script is going well. It works perfectly fine. It takes a matter of minutes and gives beautiful log and error output info.  \n\nThen I notice that I\'m not using the same standardised
variable name for the folder I\'m trying to clear out, so I edit one of my functions to bring it into line. Great, now the function should use the right variable name.  \n\nI run the script and check
my error logs. Instead of the 78 KB file I\'m expecting (from previous runs it was that size), I get a 4.9 MB file. Shit.  \n\nI check the file and see that it\'s got errors like "Unable to delete C:\
\WINDOWS. Folder not empty". Fuck.  \n\nI check other folders on the server and notice they\'re also empty. Hardly any files to be found. It\'s like a digital ghost town.\nI check my code again and se
e that I forgot to change the variable on the line that does the actual deleting:  \n\n ...\n    Remove-Item $Folder\\* -Recurse -Force -ErrorAction SilentlyContinue\n ...\n\nThe function accepted par
am([string] $Path), not $Folder.\nInstead of PowerShell going "Hey, I see a bug here. Something\'s wrong, so I\'ll stop", it goes straight ahead and does a recursive delete from the root of the C: dri
ve. Anything my script was able to delete, it did.  \n\nI immediately owned up to the problem and got our servers and storage manager to see what he could do.  \n\nThere was no server image to restore
 from. The backup software on the server wasn\'t working because.. I\'d deleted it. He first had to install the backup software before attempting to do a restore. The restore is still running. The ser
ver will be rebooted tomorrow, and if it\'s fine it\'ll be left as-is. If not it\'ll need to be re-done from scratch.  \n\nNo biggie, the server wasn\'t doing much apart from being\nTL;DR:'

**Comment by PhungVanDuy** [comment] 2023-02-17 05:10
> The error occurs half-way in the PPO training process, hope these logs are useful in locating the issue:
> 
> ```
> [losses/total_loss: 0.53 | losses/policy_loss: -0.15 | losses/value_loss: 3.41]:  54%|██████████████████████████████████████████████▉                                        | 3456/6400 [14:30:53<3:14:
> 06,  3.96s/it][RANK 0] Collecting rollouts
> [rollout 128 / 128]: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 128/128 [05:04<00:
> 00,  2.38s/it]
> [losses/total_loss: 0.30 | losses/policy_loss: 0.10 | losses/value_loss: 1.03]:  56%|█████████████████████████████████████████████████▎                                      | 3584/6400 [14:44:25<3:02:
> 54,  3.90s/it][RANK 0] Collecting rollouts
> [rollout 80 / 128]:  62%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                                          | 80/128 [03:10<01:
> 52,  2.34s/it]
> 
> Traceback (most recent call last):
>   File "/home/usr1/trlx/examples/summarize_rlhf/trlx_gptj_text_summarization.py", line 88, in reward_fn
>     original_samples = [text + post_summary_dict[text.strip()] for text in original_samples]
>   File "/home/usr1/trlx/examples/summarize_rlhf/trlx_gptj_text_summarization.py", line 88, in <listcomp>
>     original_samples = [text + post_summary_dict[text.strip()] for text in original_samples]
> KeyError: 'SUBREDDIT: r/tifu\nTITLE: TIFU by doing a recursive delete\nPOST: I\'ve been writing a PowerShell script to find and delete redundant $RECYCLE.BIN files in our thousands of user personal fo
> lders.  \n\nThe script is going well. It works perfectly fine. It takes a matter of minutes and gives beautiful log and error output info.  \n\nThen I notice that I\'m not using the same standardised
> variable name for the folder I\'m trying to clear out, so I edit one of my functions to bring it into line. Great, now the function should use the right variable name.  \n\nI run the script and check
> my error logs. Instead of the 78 KB file I\'m expecting (from previous runs it was that size), I get a 4.9 MB file. Shit.  \n\nI check the file and see that it\'s got errors like "Unable to delete C:\
> \WINDOWS. Folder not empty". Fuck.  \n\nI check other folders on the server and notice they\'re also empty. Hardly any files to be found. It\'s like a digital ghost town.\nI check my code again and se
> e that I forgot to change the variable on the line that does the actual deleting:  \n\n ...\n    Remove-Item $Folder\\* -Recurse -Force -ErrorAction SilentlyContinue\n ...\n\nThe function accepted par
> am([string] $Path), not $Folder.\nInstead of PowerShell going "Hey, I see a bug here. Something\'s wrong, so I\'ll stop", it goes straight ahead and does a recursive delete from the root of the C: dri
> ve. Anything my script was able to delete, it did.  \n\nI immediately owned up to the problem and got our servers and storage manager to see what he could do.  \n\nThere was no server image to restore
>  from. The backup software on the server wasn\'t working because.. I\'d deleted it. He first had to install the backup software before attempting to do a restore. The restore is still running. The ser
> ver will be rebooted tomorrow, and if it\'s fine it\'ll be left as-is. If not it\'ll need to be re-done from scratch.  \n\nNo biggie, the server wasn\'t doing much apart from being\nTL;DR:'
> ```

Hmm, I suggest that you use the hack above just temporarily for this fix. We may change the code base for pass extra information to reward function. https://github.com/CarperAI/trlx/issues/301

**Comment by YingHH1** [comment] 2023-02-17 05:17
I will use the hack for now. Thank you!

By the way, do you know why the PPO training uses two GPUs with one uses 59 GB and the other uses 12 GB VRAM? I assume the first GPU is for rollout by many RL and SFT model inferences to the reward model which subsequently outputs the value, and the other GPU is for RL model training (with backprop)? 

Is my understanding correct?

**Comment by PhungVanDuy** [comment] 2023-02-17 05:22
> I will use the hack for now. Thank you!
> 
> By the way, do you know why the PPO training uses two GPUs with one uses 59 GB and the other uses 12 GB VRAM? I assume the first GPU is for rollout by many RL and SFT model inferences to the reward model which subsequently outputs the value, and the other GPU is for RL model training (with backprop)?
> 
> Is my understanding correct?

Actually one is for PPO and one for the reward model. I have explained that [here](https://github.com/CarperAI/trlx/issues/266#issuecomment-1423533696).

**Comment by YingHH1** [comment] 2023-02-17 05:52
The hack has produced a similar error:

KeyError: "SUBREDDIT: r/relationships\nTITLE: [Update 2] I [18 M] want to ask out a girl [18 F] out on a date, general tips needed.\nPOST: [Original](\n(Clarification on this one, I didn't mean the one as the girl 
I wanted to marry)\nTL;DR: "

**Comment by YingHH1** [comment] 2023-02-17 06:05
> > I will use the hack for now. Thank you!
> > By the way, do you know why the PPO training uses two GPUs with one uses 59 GB and the other uses 12 GB VRAM? I assume the first GPU is for rollout by many RL and SFT model inferences to the reward model which subsequently outputs the value, and the other GPU is for RL model training (with backprop)?
> > Is my understanding correct?
> 
> Actually one is for PPO and one for the reward model. I have explained that [here](https://github.com/CarperAI/trlx/issues/266#issuecomment-1423533696).

Thank you for the reply. So just to clarify, by reward model, do you mean random samples being fed to RL model which outputs to reward model to get a score. And by PPO, do you mean training RL model by using adam for optimising the loss function L=score+KL_divergence(RL model, SFT model)?

**Comment by PhungVanDuy** [comment] 2023-02-17 06:14
> > > I will use the hack for now. Thank you!
> > > By the way, do you know why the PPO training uses two GPUs with one uses 59 GB and the other uses 12 GB VRAM? I assume the first GPU is for rollout by many RL and SFT model inferences to the reward model which subsequently outputs the value, and the other GPU is for RL model training (with backprop)?
> > > Is my understanding correct?
> > 
> > 
> > Actually one is for PPO and one for the reward model. I have explained that [here](https://github.com/CarperAI/trlx/issues/266#issuecomment-1423533696).
> 
> Thank you for the reply. So just to clarify, by reward model, do you mean random samples being fed to RL model which outputs to reward model to get a score. And by PPO, do you mean training RL model by using adam for optimising the loss function L=score+KL_divergence(RL model, SFT model)?



The reward model means calculating the reward score when we perform exploration ([rollouts](https://github.com/CarperAI/trlx/blob/724b6183202aa013a861efe723ba9f3dfa6664bc/trlx/trainer/accelerate_ppo_trainer.py#L244)) and [evaluation](https://github.com/CarperAI/trlx/blob/724b6183202aa013a861efe723ba9f3dfa6664bc/trlx/trainer/accelerate_base_trainer.py#L356), given samples (trajectories). 
PPO means training models phrase (optimization loss).

**Comment by YingHH1** [comment] 2023-02-17 09:47
> > > > I will use the hack for now. Thank you!
> > > > By the way, do you know why the PPO training uses two GPUs with one uses 59 GB and the other uses 12 GB VRAM? I assume the first GPU is for rollout by many RL and SFT model inferences to the reward model which subsequently outputs the value, and the other GPU is for RL model training (with backprop)?
> > > > Is my understanding correct?
> > > 
> > > 
> > > Actually one is for PPO and one for the reward model. I have explained that [here](https://github.com/CarperAI/trlx/issues/266#issuecomment-1423533696).
> > 
> > 
> > Thank you for the reply. So just to clarify, by reward model, do you mean random samples being fed to RL model which outputs to reward model to get a score. And by PPO, do you mean training RL model by using adam for optimising the loss function L=score+KL_divergence(RL model, SFT model)?
> 
> The reward model means calculating the reward score when we perform exploration ([rollouts](https://github.com/CarperAI/trlx/blob/724b6183202aa013a861efe723ba9f3dfa6664bc/trlx/trainer/accelerate_ppo_trainer.py#L244)) and [evaluation](https://github.com/CarperAI/trlx/blob/724b6183202aa013a861efe723ba9f3dfa6664bc/trlx/trainer/accelerate_base_trainer.py#L356), given samples (trajectories). PPO means training models phrase (optimization loss).

Thank you for the explanation and links. I am currently trying to fully grasp the whole PPO process. Just one question regarding the rollout process and the KL-divergence term in the optimization loss function: Is the KL-divergence term being approximated using the outputs produced by the rollout, as indicated in http://joschu.net/blog/kl-approx.html , since for a single prompt, multiple completions can be produced by rollout?

**Comment by PhungVanDuy** [comment] 2023-02-23 08:11
@jon-tow  before we supported input prompt (original) to fn_reward function, I propose using hashing to find the most similarity to fix this problem. I used here: https://gist.github.com/PhungVanDuy/f29c00a77d5055e926ec8f5e702c8210#file-hashing_tomatch_ppo_summarize-py-L120
Its works quite well, what do you think?

**Comment by jon-tow** [comment] 2023-02-23 16:01
@PhungVanDuy that is creative 😄 If there are few calls to hash-query then I don't think it's a terrible idea to adopt it for this example until we sort out a general fix that allows us to tie metadata to samples (issue `#301`).

**Comment by YingHH1** [comment] 2023-02-24 05:57
> @jon-tow before we supported input prompt (original) to fn_reward function, I propose using hashing to find the most similarity to fix this problem. I used here: https://gist.github.com/PhungVanDuy/f29c00a77d5055e926ec8f5e702c8210#file-hashing_tomatch_ppo_summarize-py-L120 Its works quite well, what do you think? The ratio of samples that have to use hashing is very small.

Hi, could us the user adopt this method to fix the keyError problem, at the moment?

**Comment by PhungVanDuy** [comment] 2023-02-24 07:09
> > @jon-tow before we supported input prompt (original) to fn_reward function, I propose using hashing to find the most similarity to fix this problem. I used here: https://gist.github.com/PhungVanDuy/f29c00a77d5055e926ec8f5e702c8210#file-hashing_tomatch_ppo_summarize-py-L120 Its works quite well, what do you think? The ratio of samples that have to use hashing is very small.
> 
> Hi, could us the user adopt this method to fix the keyError problem, at the moment?

Yes please, I think it can help you. Please let me know if it works!

**Comment by YingHH1** [comment] 2023-03-03 03:07
I solved this issue with workaround provided by the OP in https://github.com/CarperAI/trlx/issues/340

**Comment by PhungVanDuy** [comment] 2023-03-03 05:34
Thank you all so much for this great discussion, will close this thread.

**Closed by PhungVanDuy** 2023-03-03 05:34 UTC
Labels: bug
