### ISSUE TITLE
Cannot run PPO policy for summarization RLHF example

### ISSUE THREAD

**Issue by imraviagrawal** [CarperAI/trlx#264] opened 2023-02-02 19:09 UTC
### 🐛 Describe the bug

accelerate launch --config_file ./configs/default_accelerate_config.yaml trlx_gptj_text_summarization.py

Exception: Error: Trying to access a method that has not been registered

![Screen Shot 2023-02-02 at 11 01 57 AM](https://user-images.githubusercontent.com/24846591/216425273-f85474e4-0ef9-45ee-b864-6f652db515e7.png)

Using all of the default parameters as provided in the example. 

### Which trlX version are you using?

0.3.0

### Additional system and package information

pytorch=1.10.2+cu113, transformer=4.23.1

**Comment by PhungVanDuy** [comment] 2023-02-03 02:28
@imraviagrawal  can you try to run in the root folder like: `accelerate launch --config_file ./configs/default_accelerate_config.yaml examples/summarize_rlhf/trlx_gptj_text_summarization.py`?

**Comment by imraviagrawal** [comment] 2023-02-03 18:56
This worked, now I have another issue 

![image](https://user-images.githubusercontent.com/24846591/216684474-76a76a8b-f6a0-438f-8629-d76205630b51.png)

**Comment by PhungVanDuy** [comment] 2023-02-04 02:51
> This worked, now I have another issue, using all of the default parameters
> 
> ![image](https://user-images.githubusercontent.com/24846591/216684474-76a76a8b-f6a0-438f-8629-d76205630b51.png)

@imraviagrawal can you upgrade trlx with the newest version, I tried to re-run but cannot get this issue.

**Comment by agassi4013** [comment] 2023-02-07 11:48
> > This worked, now I have another issue, using all of the default parameters
> > ![image](https://user-images.githubusercontent.com/24846591/216684474-76a76a8b-f6a0-438f-8629-d76205630b51.png)
> 
> @imraviagrawal can you upgrade trlx with the newest version, I tried to re-run but cannot get this issue.

I run this example built yesterday, got same issue 

pytorch=1.10.0+cu113, transformer=4.26.0

trained sft and reward model based on gpt-neo-1.3B

**Comment by PhungVanDuy** [comment] 2023-02-07 12:03
> > > This worked, now I have another issue, using all of the default parameters
> > > ![image](https://user-images.githubusercontent.com/24846591/216684474-76a76a8b-f6a0-438f-8629-d76205630b51.png)
> > 
> > 
> > @imraviagrawal can you upgrade trlx with the newest version, I tried to re-run but cannot get this issue.
> 
> I run this example built yesterday, got same issue
> 
> pytorch=1.10.0+cu113, transformer=4.26.0
> 
> trained sft and reward model based on gpt-neo-1.3B

The problem above showed the different between haft and double tensor, can you review your deepspeed config with fp16?

**Comment by agassi4013** [comment] 2023-02-07 12:07
this is my ds config:

{
  "train_micro_batch_size_per_gpu": "auto",
  "fp16": {
    "enabled": true,
    "min_loss_scale": 0.5,
    "fp16_scale_tolerance": 0.25,
    "opt_level": "O2"
  },
  "zero_optimization": {
    "stage": "auto",
    "offload_optimizer": {
          "device": "auto"
      },
      "offload_param": {
          "device": "auto"
      },
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "contiguous_gradients": true
  },
  "gradient_clipping": "auto",
  "train_batch_size": "auto",
  "gradient_accumulation_steps": "auto"
}

**Comment by PhungVanDuy** [comment] 2023-02-07 12:44
@agassi4013 can you please review your build trlx version and deepspeed configs (default.yml and ds_config.json)? I just try to re-run GPT-NeoX-1.3B, but still not getting that error.  My run here: https://wandb.ai/pvduy/trlx/runs/3r0nsa7t

**Comment by agassi4013** [comment] 2023-02-07 12:51
> @agassi4013 can you please review your build trlx version and deepspeed configs (default.yml and ds_config.json)? I just try to re-run GPT-NeoX-1.3B, but still not getting that error. My run here: https://wandb.ai/pvduy/trlx/runs/3r0nsa7t

This is the default yml:
`compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: /app/trlx/examples/summarize_rlhf/configs/ds_config_trlx_acc.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
use_cpu: false
`
ds config is above, deepspeed 0.8.0, trlx 0.3.0 downloaded yesterday, I'm trying to modify fp16 setting and see if it works

**Comment by PhungVanDuy** [comment] 2023-02-07 12:53
> > @agassi4013 can you please review your build trlx version and deepspeed configs (default.yml and ds_config.json)? I just try to re-run GPT-NeoX-1.3B, but still not getting that error. My run here: https://wandb.ai/pvduy/trlx/runs/3r0nsa7t
> 
> This is the default yml:
> 
> compute_environment: LOCAL_MACHINE deepspeed_config: deepspeed_config_file: /app/trlx/examples/summarize_rlhf/configs/ds_config_trlx_acc.json zero3_init_flag: false distributed_type: DEEPSPEED downcast_bf16: 'no' dynamo_backend: 'NO' fsdp_config: {} machine_rank: 0 main_training_function: main megatron_lm_config: {} num_machines: 1 num_processes: 1 rdzv_backend: static same_network: true use_cpu: false
> 
> ds config is above, deepspeed 0.8.0, trlx 0.3.0 downloaded yesterday, I'm trying to modify fp16 setting and see if it works

Did you try to pull lastest code from master and re-install?

**Comment by agassi4013** [comment] 2023-02-07 12:56
> > > @agassi4013 can you please review your build trlx version and deepspeed configs (default.yml and ds_config.json)? I just try to re-run GPT-NeoX-1.3B, but still not getting that error. My run here: https://wandb.ai/pvduy/trlx/runs/3r0nsa7t
> > 
> > 
> > This is the default yml:
> > compute_environment: LOCAL_MACHINE deepspeed_config: deepspeed_config_file: /app/trlx/examples/summarize_rlhf/configs/ds_config_trlx_acc.json zero3_init_flag: false distributed_type: DEEPSPEED downcast_bf16: 'no' dynamo_backend: 'NO' fsdp_config: {} machine_rank: 0 main_training_function: main megatron_lm_config: {} num_machines: 1 num_processes: 1 rdzv_backend: static same_network: true use_cpu: false
> > ds config is above, deepspeed 0.8.0, trlx 0.3.0 downloaded yesterday, I'm trying to modify fp16 setting and see if it works
> 
> Did you try to pull lastest code from master and re-install?

I'll try it later

**Comment by agassi4013** [comment] 2023-02-08 07:11
> 

I rebuild the environment again, still have same issue, maybe it is caused by pytorch version?

**Comment by PhungVanDuy** [comment] 2023-02-08 07:13
> > 
> 
> I rebuild the environment again, still have same issue, maybe it is caused by pytorch version?

Can you try to run with another problem like sentiment, random walk?

**Comment by agassi4013** [comment] 2023-02-08 07:40
> > > 
> > 
> > 
> > I rebuild the environment again, still have same issue, maybe it is caused by pytorch version?
> 
> Can you try to run with another problem like sentiment, random walk (use deepspeed)?

I tried deepspeed ppo_randomwalks

there's an error:
![image](https://user-images.githubusercontent.com/35730805/217465009-60fed25a-da7d-4654-ab0f-5d8615402f99.png)

**Comment by agassi4013** [comment] 2023-02-08 09:15
> > 
> 
> I rebuild the environment again, still have same issue, maybe it is caused by pytorch version?

updated to torch 1.12.1, bug fixed

**Comment by PhungVanDuy** [comment] 2023-02-08 09:17
> > > 
> > 
> > 
> > I rebuild the environment again, still have same issue, maybe it is caused by pytorch version?
> 
> updated to torch 1.12.1, bug fixed

great to hear that! we will note it for the requirements file. Thank you so much. Can you try to re-run with summarization as well, I will close this issue then.

**Comment by agassi4013** [comment] 2023-02-08 09:20
> > > > 
> > > 
> > > 
> > > I rebuild the environment again, still have same issue, maybe it is caused by pytorch version?
> > 
> > 
> > updated to torch 1.12.1, bug fixed
> 
> great to hear that! we will note it for the requirements file. Thank you so much. Can you try to re-run with summarization as well, I will close this issue then.

I'm running ppo for summarization now, will take a few hours to finish

**Comment by l1f14bscs0388** [comment] 2023-02-08 13:01
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/drive/MyDrive/New_trlx/trlx/examples/summarize_rlhf/trlx_gptj_text_ │
│ summarization.py:123 in <module>                                             │
│                                                                              │
│   120 │   for i in range(len(val_prompts)):                                  │
│   121 │   │   post_summary_dict[val_prompts[i]] = val_summaries[i]           │
│   122 │                                                                      │
│ ❱ 123 │   trainer = trlx.train(                                              │
│   124 │   │   reward_fn=reward_fn,                                           │
│   125 │   │   prompts=train_prompts,                                         │
│   126 │   │   eval_prompts=val_prompts[0:253],  # sampling 1000 validation p │
│                                                                              │
│ /content/drive/MyDrive/New_trlx/trlx/trlx/trlx.py:73 in train                │
│                                                                              │
│    70 │   if model_path:                                                     │
│    71 │   │   config.model.model_path = model_path                           │
│    72 │                                                                      │
│ ❱  73 │   trainer = get_trainer(config.train.trainer)(                       │
│    74 │   │   config=config,                                                 │
│    75 │   │   reward_fn=reward_fn,                                           │
│    76 │   │   metric_fn=metric_fn,                                           │
│                                                                              │
│ /content/drive/MyDrive/New_trlx/trlx/trlx/trainer/accelerate_ppo_trainer.py: │
│ 46 in __init__                                                               │
│                                                                              │
│    43 │   │   Args:                                                          │
│    44 │   │   │   config: Config                                             │
│    45 │   │   """                                                            │
│ ❱  46 │   │   super().__init__(config, **kwargs)                             │
│    47 │   │                                                                  │
│    48 │   │   # Setup rollout logging                                        │
│    49 │   │   if config.train.rollout_logging_dir is not None:               │
│                                                                              │
│ /content/drive/MyDrive/New_trlx/trlx/trlx/trainer/accelerate_base_trainer.py │
│ :49 in __init__                                                              │
│                                                                              │
│    46 │   def __init__(self, config, **kwargs):  # noqa: C901                │
│    47 │   │   super().__init__(config, **kwargs)                             │
│    48 │   │   self.max_length = config.train.seq_length                      │
│ ❱  49 │   │   self.accelerator = Accelerator(log_with=config.train.tracker,  │
│    50 │   │                                                                  │
│    51 │   │   if self.accelerator.state.deepspeed_plugin is not None:        │
│    52 │   │   │   # by accelerate's default, arguments in `model.forward` wo │
│                                                                              │
│ /usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py:250 in      │
│ __init__                                                                     │
│                                                                              │
│    247 │   │                                                                 │
│    248 │   │   if deepspeed_plugin is None:  # init from env variables       │
│    249 │   │   │   deepspeed_plugin = (                                      │
│ ❱  250 │   │   │   │   DeepSpeedPlugin() if os.environ.get("ACCELERATE_USE_D │
│    251 │   │   │   )                                                         │
│    252 │   │   else:                                                         │
│    253 │   │   │   assert isinstance(                                        │
│ in __init__                                                                  │
│                                                                              │
│ /usr/local/lib/python3.8/dist-packages/accelerate/utils/dataclasses.py:427   │
│ in __post_init__                                                             │
│                                                                              │
│    424 │   │   │   or isinstance(self.hf_ds_config, HfDeepSpeedConfig)       │
│    425 │   │   ):                                                            │
│    426 │   │   │   if not isinstance(self.hf_ds_config, HfDeepSpeedConfig):  │
│ ❱  427 │   │   │   │   self.hf_ds_config = HfDeepSpeedConfig(self.hf_ds_conf │
│    428 │   │   │   if "gradient_accumulation_steps" not in self.hf_ds_config │
│    429 │   │   │   │   self.hf_ds_config.config["gradient_accumulation_steps │
│    430 │   │   │   if "zero_optimization" not in self.hf_ds_config.config:   │
│                                                                              │
│ /usr/local/lib/python3.8/dist-packages/accelerate/utils/deepspeed.py:53 in   │
│ __init__                                                                     │
│                                                                              │
│    50 │   │   │   │   config = json.load(f)                                  │
│    51 │   │   else:                                                          │
│    52 │   │   │   try:                                                       │
│ ❱  53 │   │   │   │   config_decoded = base64.urlsafe_b64decode(config_file_ │
│    54 │   │   │   │   config = json.loads(config_decoded)                    │
│    55 │   │   │   except (UnicodeDecodeError, AttributeError):               │
│    56 │   │   │   │   raise ValueError(                                      │
│                                                                              │
│ /usr/lib/python3.8/base64.py:133 in urlsafe_b64decode                        │
│                                                                              │
│   130 │   """                                                                │
│   131 │   s = _bytes_from_decode_data(s)                                     │
│   132 │   s = s.translate(_urlsafe_decode_translation)                       │
│ ❱ 133 │   return b64decode(s)                                                │
│   134                                                                        │
│   135                                                                        │
│   136                                                                        │
│                                                                              │
│ /usr/lib/python3.8/base64.py:87 in b64decode                                 │
│                                                                              │
│    84 │   │   s = s.translate(bytes.maketrans(altchars, b'+/'))              │
│    85 │   if validate and not re.fullmatch(b'[A-Za-z0-9+/]*={0,2}', s):      │
│    86 │   │   raise binascii.Error('Non-base64 digit found')                 │
│ ❱  87 │   return binascii.a2b_base64(s)                                      │
│    88                                                                        │
│    89                                                                        │
│    90 def standard_b64encode(s):                                             │
╰──────────────────────────────────────────────────────────────────────────────╯
Error: Invalid base64-encoded string: number of data characters (41) cannot be 1
more than a multiple of 4
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 14913) of binary: /usr/bin/python3

**Comment by agassi4013** [comment] 2023-02-09 07:48
> 



> > > > > 
> > > > 
> > > > 
> > > > I rebuild the environment again, still have same issue, maybe it is caused by pytorch version?
> > > 
> > > 
> > > updated to torch 1.12.1, bug fixed
> > 
> > 
> > great to hear that! we will note it for the requirements file. Thank you so much. Can you try to re-run with summarization as well, I will close this issue then.
> 
> I'm running ppo for summarization now, will take a few hours to finish

I have run it successfully

**Comment by l1f14bscs0388** [comment] 2023-02-09 07:58
> > 
> 
> > > > > > 
> > > > > 
> > > > > 
> > > > > I rebuild the environment again, still have same issue, maybe it is caused by pytorch version?
> > > > 
> > > > 
> > > > updated to torch 1.12.1, bug fixed
> > > 
> > > 
> > > great to hear that! we will note it for the requirements file. Thank you so much. Can you try to re-run with summarization as well, I will close this issue then.
> > 
> > 
> > I'm running ppo for summarization now, will take a few hours to finish
> 
> I have run it successfully

it's not a torch issue @agassi4013

**Comment by agassi4013** [comment] 2023-02-09 08:02
> > > 
> > 
> > 
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > I rebuild the environment again, still have same issue, maybe it is caused by pytorch version?
> > > > > 
> > > > > 
> > > > > updated to torch 1.12.1, bug fixed
> > > > 
> > > > 
> > > > great to hear that! we will note it for the requirements file. Thank you so much. Can you try to re-run with summarization as well, I will close this issue then.
> > > 
> > > 
> > > I'm running ppo for summarization now, will take a few hours to finish
> > 
> > 
> > I have run it successfully
> 
> it's not a torch issue @agassi4013 @agassi4013 can you tell me what is your GPU memory and how many GPU's you are used

Tesla V100 32G, 4 GPUs for sft and reward model training, single GPU for PPO training

**Comment by l1f14bscs0388** [comment] 2023-02-09 08:11
> > > > 
> > > 
> > > 
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > I rebuild the environment again, still have same issue, maybe it is caused by pytorch version?
> > > > > > 
> > > > > > 
> > > > > > updated to torch 1.12.1, bug fixed
> > > > > 
> > > > > 
> > > > > great to hear that! we will note it for the requirements file. Thank you so much. Can you try to re-run with summarization as well, I will close this issue then.
> > > > 
> > > > 
> > > > I'm running ppo for summarization now, will take a few hours to finish
> > > 
> > > 
> > > I have run it successfully
> > 
> > 
> > it's not a torch issue @agassi4013 @agassi4013 can you tell me what is your GPU memory and how many GPU's you are used
> 
> Tesla V100 32G, 4 GPUs for sft and reward model training, single GPU for PPO training

for PPO You used V100 32GB 1 GPU can you share **setup.cfg** file

**Comment by l1f14bscs0388** [comment] 2023-02-09 09:52
> accelerate

@agassi4013 Can you tell me accelerate version.

**Comment by agassi4013** [comment] 2023-02-09 11:13
> > accelerate
> 
> @agassi4013 Can you tell me accelerate version.

0.16.0

**Comment by l1f14bscs0388** [comment] 2023-02-09 11:57
> > > accelerate
> > 
> > 
> > @agassi4013 Can you tell me accelerate version.
> 
> 0.16.0

thanks for your help now my error is solved I changed accelerate version 0.16.0 to 0.15.0 @agassi4013 @PhungVanDuy

**Closed** 2023-02-09 12:28 UTC
Labels: bug
